static const char enum_gen_cpp_templates_txt[2851] =
    "EnumGenerationProlog                    = #pragma once\\n\n"
    "EnumGenerationEpilog                    = \\n\n"
    "\n"
    "EnumDeclarationBegin                    = enum $(CLASS) $(ENAMNAME)\n"
    "EnumDeclarationWithUnderlyingTypeBegin  = \" enum $(CLASS) $(ENAMNAME) : $(UNDERLYING)\"\n"
    "EnumDeclarationClassKeyword             = class\n"
    "\n"
    "TypeCast                                = ($(UNDERLYING))($(ITEMVAL))\n"
    "\n"
    "EnumScopeBegin                          = \\n$(INDENT){\n"
    "EnumScopeEnd                            = \\n\\n$(INDENT)}; // $(DECLBEGIN)\\n\n"
    "\n"
    "EnumItemDeclarationSeparatorBeforeFirst = \\n\n"
    "EnumItemDeclarationSeparatorBefore      = ,\\n\n"
    "EnumItemDeclarationSeparatorAfter       = \"\"\n"
    "\n"
    "EnumItemDeclaration                     = \" $(ITEMNAME) = $(ITEMVAL)$(ITEMCOMMENT)\"\n"
    "EnumItemComment                         = \" /* $(ITEMCOMMENTTEXT) */\"\n"
    "EnumFlagsDeclaration                    = MARTY_CPP_MAKE_ENUM_FLAGS($(ENAMNAME))\\n\n"
    "\n"
    "EnumSerializationBegin                  = \" MARTY_CPP_ENUM$(PPCLASS)_SERIALIZE_BEGIN( $(ENAMNAME), $(MAPTYPE), $(UPPERFLAG) )\\n\"\n"
    "EnumSerializationEnd                    = \" MARTY_CPP_ENUM$(PPCLASS)_SERIALIZE_END( $(ENAMNAME), $(MAPTYPE), $(UPPERFLAG) )\\n\"\n"
    "EnumSerializationItem                   = \" MARTY_CPP_ENUM$(PPCLASS)_SERIALIZE_ITEM( $(ITEMNAME), $(ITEMVAL) )\"\n"
    "\n"
    "EnumDeserializationBegin                = \" MARTY_CPP_ENUM$(PPCLASS)_DESERIALIZE_BEGIN( $(ENAMNAME), $(MAPTYPE), $(UPPERFLAG) )\\n\"\n"
    "EnumDeserializationEnd                  = \" MARTY_CPP_ENUM$(PPCLASS)_DESERIALIZE_END( $(ENAMNAME), $(MAPTYPE), $(UPPERFLAG) )\\n\"\n"
    "EnumDeserializationItem                 = \" MARTY_CPP_ENUM$(PPCLASS)_DESERIALIZE_ITEM( $(ITEMNAME), $(ITEMVAL) )\"\n"
    "\n"
    "EnumItemSerializeBeforeFirst            = \"\"\n"
    "EnumItemSerializeBefore                 = \"\"\n"
    "EnumItemSerializeAfter                  = \";\\n\"\n"
    "\n"
    "EnumSerializeSet                        = \"MARTY_CPP_ENUM$(PPCLASS)_SERIALIZE_SET($(ENAMNAME), $(SETTYPE))\\n\"\n"
    "EnumDeserializeSet                      = \"MARTY_CPP_ENUM$(PPCLASS)_DESERIALIZE_SET($(ENAMNAME), $(SETTYPE))\\n\"\n"
    "EnumSerializeSetType                    = \"std::set\"\n"
    "\n"
    "EnumUserIncludeFormat                   = #include \\\"$(FILENAME)\\\"\n"
    "EnumSystemIncludeFormat                 = #include <$(FILENAME)>\n"
    "\n"
    "EnumIncludesBefore                      = \\n\n"
    "EnumIncludesAfter                       = \\n\n"
    "EnumIncludesEntrySeparator              = \\n\n"
    "EnumIncludesGroupSeparator              = \\n\n"
    "EnumIncludesBlockSeparator              = \\n\n"
    "\n"
    "EnumDeclarationIncludes                 = marty_cpp/marty_ns.h\n"
    "EnumSerializationIncludes               = <unordered_map>, <map>, <string>, <exception>, <stdexcept>, marty_cpp/marty_enum.h\n"
    "EnumDeserializationIncludes             = <unordered_map>, <map>, <string>, <exception>, <stdexcept>, marty_cpp/marty_enum.h\n"
    "EnumFlagIncludes                        = marty_cpp/marty_flags.h\n"
    "EnumSetIncludes                         = <unordered_set>, <set>\n"
    "\n"
    "\n"
    "\n"
    ;

static const unsigned enum_gen_cpp_templates_txt_size = 2850; /* Not including terminating zero */

static const char* enum_gen_cpp_templates_txt_filename = "enum_gen_cpp_templates.txt";
